name: Publish Package to npmjs

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your desired Node.js version
          registry-url: 'https://registry.npmjs.org/' # Use the official registry

      - name: Install dependencies
        run: npm ci # Use ci for cleaner installs in CI

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public # Add --access public if publishing a scoped package for the first time
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use the secret token
